import { OrderEntity } from '../../types/Stock.type';

export const data: OrderEntity[] = [
  {
    id: 1,
    product: {id: 1, name: 'Product 01', price: 19.9},
    quantity: 10,
    statusId:1,
    status:'Pendente',
  },
  {
    id: 2,
    product: {id: 1, name: 'Product 02', price: 19.9},
    quantity: 10,
    statusId:1,
    status:'Pendente',
  },
  {
    id: 3,
    product: {id: 1, name: 'Product 03', price: 19.9},
    quantity: 10,
    statusId:1,
    status:'Pendente',
  },
  {
    id: 4,
    product: {id: 1, name: 'Product 04', price: 19.9},
    quantity: 10,
    statusId:2,
    status:'Confirmada',
  },
  {
    id: 5,
    product: {id: 1, name: 'Product 05', price: 19.9},
    quantity: 10,
    statusId:2,
    status:'Confirmada',
  },
];

//50 us states array
export const states = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
  'Puerto Rico',
];