import { ProductEntity } from '../../types/Stock.type';

export const data: ProductEntity[] = [
  {
    id: 1,
    name: 'Product 01',
    price: 19.9,
  },
  {
    id: 2,
    name: 'Product 01',
    price: 19.9,
  },
  {
    id: 3,
    name: 'Product 01',
    price: 19.9,
  },
  {
    id: 4,
    name: 'Product 01',
    price: 19.9,
  },
  {
    id: 5,
    name: 'Product 01',
    price: 19.9,
  },
];

//50 us states array
export const states = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
  'Puerto Rico',
];